name: Contrôle Qualité PHP

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          # On demande spécifiquement une version qui comprend 'setParallelConfig'
          tools: php-cs-fixer:3.64.0 
          coverage: none

      - name: Validate PHP syntax (Linter)
        run: |
          find . -type f -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l

      - name: Run PHP-CS-Fixer
        # ATTENTION : On appelle 'php-cs-fixer' TOUT COURT.
        # Ne mettez surtout pas './php-cs-fixer.phar' ici, 
        # sinon il utilisera votre vieux fichier cassé.
        run: php-cs-fixer fix --dry-run --diff --ansi