name: Contrôle Qualité PHP

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Validate PHP syntax (Linter)
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Run PHP-CS-Fixer (PHP-CS-Fixer)
        run: |
          curl -L https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v3.40.0/php-cs-fixer.phar -o php-cs-fixer.phar
          php php-cs-fixer.phar fix --dry-run --diff --rules=@PSR12 .
